FROM node:24-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.base.json ./
COPY packages/shared ./packages/shared
COPY packages/locales ./packages/locales
COPY apps/ui ./apps/ui

RUN npm ci

RUN npm run build --workspace=apps/ui

FROM nginx:alpine
COPY --from=builder /app/apps/ui/dist /usr/share/nginx/html

COPY apps/ui/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
