services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
    env_file:
      - apps/api/.env

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - '5173:80'
    depends_on:
      - api
