name: CI/CD – Build & Deploy All

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'docker-compose.yml'

env:
  REGISTRY: ghcr.io
  DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: api
            context: apps/api
            dockerfile: Dockerfile.api
            image: finper-api
          - name: ui
            context: apps/ui
            dockerfile: Dockerfile.ui
            image: finper-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" \ | docker login ${{ env.REGISTRY }} -u "${{ github.repository_owner }}" --password-stdin

      - name: Build & Push ${{ matrix.service.name }}
        run: |
          docker build \
            -f ${{ matrix.service.dockerfile }} \
            -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service.image }}:latest \
            ${{ matrix.service.context }}
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service.image }}:latest

  deploy:
    name: Deploy
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DATABASE_URL=mongodb://${{ secrets.MONGO_APP_USER }}:${{ secrets.MONGO_APP_PASSWORD }}@mongodb:27017/${{ secrets.MONGO_DB }}?authSource=admin" > .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TINKOFF_TOKEN=${{ secrets.TINKOFF_TOKEN }}" >> .env
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "UI_HOST=${{ secrets.UI_HOST }}" >> .env

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server
        run: |
          scp -o StrictHostKeyChecking=no .env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{secrets.DEPLOY_DIR}}
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{secrets.DEPLOY_DIR}}
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
            cd $DEPLOY_DIR

            cat > mongo-init.js << INIT
            db.createUser({
              user:   "${{ secrets.MONGO_APP_USER }}",
              pwd:    "${{ secrets.MONGO_APP_PASSWORD }}",
              roles: [ { role: "readWrite", db: "${{ secrets.MONGO_DB }}" } ]
            });
            INIT

            docker compose pull
            docker compose up -d --build

            docker system prune -f
          EOF
